# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_mbgd_lm <- function(X, y, beta_init, eps = 1e-4, backtrack = FALSE, step_size = 0.01, max_iter = 10000L, alpha = 0.25, backtracking_beta = 0.8, batch_size = 20L) {
    .Call(`_bgd_rcpp_mbgd_lm`, X, y, beta_init, eps, backtrack, step_size, max_iter, alpha, backtracking_beta, batch_size)
}

rcpp_Momentum_lm <- function(X, y, beta_init, eps = 1e-4, backtrack = FALSE, step_size = 0.01, max_iter = 10000L, alpha = 0.25, backtracking_beta = 0.8, batch_size = 1L, rho = 0.9) {
    .Call(`_bgd_rcpp_Momentum_lm`, X, y, beta_init, eps, backtrack, step_size, max_iter, alpha, backtracking_beta, batch_size, rho)
}

